

export default {
  home: 'home',
  favorite: "favorite",
  favorites: 'favorites',
  add_to_favorites: 'add to favorites',
  loading_data: 'Retrieving datas...',
  cryptocurrency_prices: 'Cryptocurrency Prices',
  cryptocurrency_favorites: 'Crypto Favorites',
  no_result: "No result found.",
  name: "Name",
  current_price: "Price",
  market_cap: "Market Cap",
  total_volume: "Total Volume",
  last_7_day: "Last 7 Days",
  search_a_name: "Search a name",
  no_graphic_found: "No graphic found",
  page_not_found: "Page Not Found",
  go_home: "Click here to go back home",
  go_back: "Or click where to go back in your router history",
  adapt_meta: "It's better in production to adapt meta head for SEO, and auto-redirect.",
  dark_mode: 'Dark Mode',
  light_mode: 'Light Mode',
};
