
export default {
  home: 'accueil',
  favorite: "favori",
  favorites: 'favoris',
  add_to_favorites: 'Ajouter aux favoris',
  loading_data: 'Récupération des données',
  cryptocurrency_prices: 'Prix des cryptomonnaies',
  cryptocurrency_favorites: 'Crypto Favoris',
  no_result: "Aucun résultat trouvé",
  name: "Nom",
  current_price: "Prix",
  market_cap: "Market Cap",
  total_volume: "Volume Total",
  last_7_day: "Derniers 7 jours",
  search_a_name: "Rechercher un nom",
  no_graphic_found: "Aucun graphique disponible",
  page_not_found: "Page non trouvée",
  go_home: "Cliquez ici pour rentrer chez vous",
  go_back: "Ou cliquez où revenir dans l'historique de votre routeur",
  adapt_meta: "Il est préférable en production d'adapter la méta-tête pour le référencement et la redirection automatique.",
  dark_mode: 'Mode sombre',
  light_mode: 'Mode lumière',
};
